[project]
name = "lapdrop-stealth-surgeon"
version = "0.0.0"
description = "Placeholder package for the LapDrop: Stealth Surgeon Python rebuild."
authors = [
  { name = "LapDrop Team" }
]
requires-python = ">=3.11"
dependencies = []

[tool.ruff]
line-length = 100
